# Generated by Django 5.1.1 on 2024-12-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_tarefa',
            name='done',
            field=models.CharField(choices=[('Fazendo', 'fazendo'), ('Feito', 'feito')], default='Fazendo', max_length=7),
        ),
    ]
