# Generated by Django 5.1.1 on 2024-12-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lista_tarefa_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lista_tarefa',
            new_name='Lista_tarefas',
        ),
    ]
