# Generated by Django 5.1.1 on 2025-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile/default-avatar.jpg', upload_to='profile_pictures/'),
        ),
    ]
